### ISSUE TITLE
pass movement changes into shape.draw() method

### ISSUE THREAD

**Issue by isaachulvey** [40dm/gam#23]
As it stands, PR https://github.com/40dm/gam/pull/21 adds the logic and opportunity to move shapes, but in order to successfully move a shape, we'll need to pass in the deltaX and deltaY variables to the draw() method for whatever shape(s) we want to move.

**Comment by jmarshvaile** [comment]
Nice!

Instead of passing coords through `.draw()` I propose modifying the shape classes to include a `.pos.x` and `.pos.y` getter and setter and then either calling `.draw()` in the pos setter to redraw after pos change or leave it up to the dev to call `.draw()` in the main script.

**Comment by jmarshvaile** [comment]
@isaachulvey

**Comment by jmarshvaile** [comment]
progress currently blocked by issue https://github.com/40dm/gam/issues/26
