### ISSUE TITLE
fix an edge case where holding a button stops moving the character

### ISSUE THREAD

**Issue by jmarshvaile** [40dm/gam#39]
Movements stop registering while holding a button.

Steps to replicate:
- Press and hold W
- While still holding W, press and hold D
- Now release D (still holding W

The W key will no longer register movement until you release and press again.

**Comment by isaachulvey** [comment]
Here's the behavior and my understanding of it:

1. User presses and holds W.
2. Shape begins moving up.
3. User presses D.
4. Shape begins moving left and continues moving up.
5. User releases D.
6. Shape stops moving even though W is still held.

In the code what happens is:
1. `keys = {W: true}`
2. Shape begins moving up.
3. `keys = {W: true, D: true}`
4. Shape begins moving left and continues moving up.
5. `keys = {W: true, D: false}`
6. Shape stops moving entirely.

What I'm thinking is there needs to be some kind of check, perhaps in the keysReleased function that checks the keys dictionary to see if there are any remaining true values. If so, then continue updating the position of the held key. If all dictionary values are false, then no further action is needed.

Thoughts @jmarshvaile?

**Comment by isaachulvey** [comment]
Ok, so I've got something that sorta works but also still fails in certain conditions. I'll outline those here.

What is happening that's causing it to fail is that somehow an undefined value is being inserted into the keys object.

Example: 
`{65: false, 68: false, 83: false, 87: false, undefined: true}`

Essentially the way my code works is that when keysReleased fires, it checks the keys object for any true values, if/when it finds a true value (meaning another key is still pressed down), it figures out which key is still pressed and then calls the keysPressed function passing along the specific key still pressed.

BUT somehow, an undefined key is added to the object and is being set to true which is somehow breaking things. I think.

The best way to recreate this is to press and hold W, then press A, then release A. 

The keys object should still maintain that W is pressed (true) and call keysPressed(keyW). However, that doesn't work.

**Comment by jmarshvaile** [comment]
Not sure about the undefined or the problem as a whole, but:

if you want to check all values in an object, you can use ` Object.values()` to get an array of values. Then use `.some()` to check for one or more `true` values.

```
keys = {1: true, 2: false};
results = Object.values(keys).some(Boolean);
console.log(results);
```

**Comment by jmarshvaile** [comment]
The issue was we were writing x/y updates on the interval that was determined by the browser keypress listener. By moving position updates to a a function and calling that function in regular 60fps intervals (with `setInterval`), the updates were no longer dependent on built in key press behavior.
